import { Currency } from '../../../../types'

export const FALLBACK_CURRENCIES: Currency[] = [
  {
    code: 'GBP',
    description: 'British Pound',
    fractionDigits: 2,
    countryCode: 'GB',
  },
  {
    code: 'EUR',
    description: 'Euro',
    fractionDigits: 2,
    countryCode: 'EU',
  },
  {
    code: 'USD',
    description: 'United States Dollar',
    fractionDigits: 2,
    countryCode: 'US',
  },
  {
    code: 'AUD',
    description: 'Australian Dollar',
    fractionDigits: 2,
    countryCode: 'AU',
  },
  {
    code: 'CAD',
    description: 'Canadian Dollar',
    fractionDigits: 2,
    countryCode: 'CA',
  },
  {
    code: 'CZK',
    description: 'Czech Koruna',
    fractionDigits: 2,
    countryCode: 'CZ',
  },
  {
    code: 'DKK',
    description: 'Danish Krone',
    fractionDigits: 2,
    countryCode: 'DK',
  },
  {
    code: 'JPY',
    description: 'Japanese Yen',
    fractionDigits: 0,
    countryCode: 'JP',
  },
  {
    code: 'MXN',
    description: 'Mexican Peso',
    fractionDigits: 2,
    countryCode: 'MX',
  },
  {
    code: 'PLN',
    description: 'Polish Zloty',
    fractionDigits: 2,
    countryCode: 'PL',
  },
  {
    code: 'RON',
    description: 'Romanian Leu',
    fractionDigits: 2,
    countryCode: 'RO',
  },
  {
    code: 'SEK',
    description: 'Swedish Krona',
    fractionDigits: 2,
    countryCode: 'SE',
  },
  {
    code: 'THB',
    description: 'Thai Baht',
    fractionDigits: 2,
    countryCode: 'TH',
  },
  {
    code: 'AED',
    description: 'United Arab Emirates Dirham',
    fractionDigits: 2,
    countryCode: 'AE',
  },
  {
    code: 'CHF',
    description: 'Swiss Franc',
    fractionDigits: 2,
    countryCode: 'CH',
  },
  {
    code: 'HKD',
    description: 'Hong Kong Dollar',
    fractionDigits: 2,
    countryCode: 'HK',
  },
  {
    code: 'HUF',
    description: 'Hungarian Forint',
    fractionDigits: 2,
    countryCode: 'HU',
  },
  {
    code: 'ILS',
    description: 'Israeli New Sheqel',
    fractionDigits: 2,
    countryCode: 'IL',
  },
  {
    code: 'NOK',
    description: 'Norwegian Krone',
    fractionDigits: 2,
    countryCode: 'NO',
  },
  {
    code: 'NZD',
    description: 'New Zealand Dollar',
    fractionDigits: 2,
    countryCode: 'NZ',
  },
  {
    code: 'SGD',
    description: 'Singapore Dollar',
    fractionDigits: 2,
    countryCode: 'SG',
  },
  {
    code: 'TRY',
    description: 'Turkish Lira',
    fractionDigits: 2,
    countryCode: 'TR',
  },
  {
    code: 'ZAR',
    description: 'South African Rand',
    fractionDigits: 2,
    countryCode: 'ZA',
  },
  {
    code: 'SAR',
    description: 'Saudi Arabian Riyal',
    fractionDigits: 2,
    countryCode: 'SA',
  },
  {
    code: 'BGN',
    description: 'Bulgarian Lev',
    fractionDigits: 2,
    countryCode: 'BG',
  },
  {
    code: 'QAR',
    description: 'Qatari Riyal',
    fractionDigits: 2,
    countryCode: 'QA',
  },
  {
    code: 'ALL',
    description: 'Albanian Lek',
    fractionDigits: 2,
    countryCode: 'AL',
  },
  {
    code: 'AFN',
    description: 'Afghan Afghani',
    fractionDigits: 2,
    countryCode: 'AF',
  },
  {
    code: 'ARS',
    description: 'Argentine Peso',
    fractionDigits: 2,
    countryCode: 'AR',
  },
  {
    code: 'AWG',
    description: 'Aruban or Dutch Guilder',
    fractionDigits: 2,
    countryCode: 'AW',
  },
  {
    code: 'AZN',
    description: 'Azerbaijani New Manat',
    fractionDigits: 2,
    countryCode: 'AZ',
  },
  {
    code: 'BSD',
    description: 'Bahamian Dollar',
    fractionDigits: 2,
    countryCode: 'BS',
  },
  {
    code: 'BBD',
    description: 'Barbadian or Bajan Dollar',
    fractionDigits: 2,
    countryCode: 'BB',
  },
  {
    code: 'BZD',
    description: 'Belizean Dollar',
    fractionDigits: 2,
    countryCode: 'BZ',
  },
  {
    code: 'BMD',
    description: 'Bermudian Dollar',
    fractionDigits: 2,
    countryCode: 'BM',
  },
  {
    code: 'BOB',
    description: 'Bolivian Boliviano',
    fractionDigits: 2,
    countryCode: 'BO',
  },
  {
    code: 'BAM',
    description: 'Bosnia Convertible Marka',
    fractionDigits: 2,
    countryCode: 'BA',
  },
  {
    code: 'BWP',
    description: 'Botswana Pula',
    fractionDigits: 2,
    countryCode: 'BW',
  },
  {
    code: 'BRL',
    description: 'Brazilian Real',
    fractionDigits: 2,
    countryCode: 'BR',
  },
  {
    code: 'BND',
    description: 'Bruneian Dollar',
    fractionDigits: 2,
    countryCode: 'BN',
  },
  {
    code: 'KHR',
    description: 'Cambodian Riel',
    fractionDigits: 2,
    countryCode: 'KH',
  },
  {
    code: 'KYD',
    description: 'Caymanian Dollar',
    fractionDigits: 2,
    countryCode: 'KY',
  },
  {
    code: 'CLP',
    description: 'Chilean Peso',
    fractionDigits: 0,
    countryCode: 'CL',
  },
  {
    code: 'CNY',
    description: 'Chinese Yuan Renminbi',
    fractionDigits: 2,
    countryCode: 'CN',
  },
  {
    code: 'COP',
    description: 'Colombian Peso',
    fractionDigits: 2,
    countryCode: 'CO',
  },
  {
    code: 'CRC',
    description: 'Costa Rican Colon',
    fractionDigits: 2,
    countryCode: 'CR',
  },
  {
    code: 'HRK',
    description: 'Croatian Kuna',
    fractionDigits: 2,
    countryCode: 'HR',
  },
  {
    code: 'CUC',
    description: 'Cuban Convertible Peso',
    fractionDigits: 2,
    countryCode: 'CU',
  },
  {
    code: 'DOP',
    description: 'Dominican Peso',
    fractionDigits: 2,
    countryCode: 'DO',
  },
  {
    code: 'XCD',
    description: 'East Caribbean Dollar',
    fractionDigits: 2,
    countryCode: 'KN',
  },
  {
    code: 'EGP',
    description: 'Egyptian Pound',
    fractionDigits: 2,
    countryCode: 'EG',
  },
  {
    code: 'SVC',
    description: 'Salvadoran Colon',
    fractionDigits: 2,
    countryCode: 'SV',
  },
  {
    code: 'FKP',
    description: 'Falkland Island Pound',
    fractionDigits: 2,
    countryCode: 'FK',
  },
  {
    code: 'FJD',
    description: 'Fijian Dollar',
    fractionDigits: 2,
    countryCode: 'FJ',
  },
  {
    code: 'GIP',
    description: 'Gibraltar Pound',
    fractionDigits: 2,
    countryCode: 'GI',
  },
  {
    code: 'GTQ',
    description: 'Guatemalan Quetzal',
    fractionDigits: 2,
    countryCode: 'GT',
  },
  {
    code: 'HNL',
    description: 'Honduran Lempira',
    fractionDigits: 2,
    countryCode: 'HN',
  },
  {
    code: 'ISK',
    description: 'Icelandic Krona',
    fractionDigits: 0,
    countryCode: 'IS',
  },
  {
    code: 'INR',
    description: 'Indian Rupee',
    fractionDigits: 2,
    countryCode: 'IN',
  },
  {
    code: 'IDR',
    description: 'Indonesian Rupiah',
    fractionDigits: 2,
    countryCode: 'ID',
  },
  {
    code: 'JMD',
    description: 'Jamaican Dollar',
    fractionDigits: 2,
    countryCode: 'JM',
  },
  {
    code: 'KZT',
    description: 'Kazakhstani Tenge',
    fractionDigits: 2,
    countryCode: 'KZ',
  },
  {
    code: 'KRW',
    description: 'South Korean Won',
    fractionDigits: 0,
    countryCode: 'KR',
  },
  {
    code: 'MAD',
    description: 'Moroccan Dirham',
    fractionDigits: 2,
    countryCode: 'MA',
  },
  {
    code: 'RUB',
    description: 'Russian Ruble',
    fractionDigits: 2,
    countryCode: 'RU',
  },
  {
    code: 'MYR',
    description: 'Malaysian Ringgit',
    fractionDigits: 2,
    countryCode: 'MY',
  },
  {
    code: 'PHP',
    description: 'Philippine Peso',
    fractionDigits: 2,
    countryCode: 'PH',
  },
  {
    code: 'AMD',
    description: 'Armenian Dram',
    fractionDigits: 2,
    countryCode: 'AM',
  },
  {
    code: 'ANG',
    description: 'Dutch Antilles Guilder',
    fractionDigits: 2,
    countryCode: 'CW',
  },
  {
    code: 'AOA',
    description: 'Angolan Kwanza',
    fractionDigits: 2,
    countryCode: 'AO',
  },
  {
    code: 'BDT',
    description: 'Bangladeshi Taka',
    fractionDigits: 2,
    countryCode: 'BD',
  },
  {
    code: 'BHD',
    description: 'Bahraini Dinar',
    fractionDigits: 3,
    countryCode: 'BH',
  },
  {
    code: 'BYN',
    description: 'Belarusian Ruble',
    fractionDigits: 2,
    countryCode: 'BY',
  },
  {
    code: 'CVE',
    description: 'Cape Verdean Escudo',
    fractionDigits: 2,
    countryCode: 'CV',
  },
  {
    code: 'DZD',
    description: 'Algerian Dinar',
    fractionDigits: 2,
    countryCode: 'DZ',
  },
  {
    code: 'ETB',
    description: 'Ethiopian Birr',
    fractionDigits: 2,
    countryCode: 'ET',
  },
  {
    code: 'GEL',
    description: 'Georgian Lari',
    fractionDigits: 2,
    countryCode: 'GE',
  },
  {
    code: 'GHS',
    description: 'Ghanaian Cedi',
    fractionDigits: 2,
    countryCode: 'GH',
  },
  {
    code: 'GMD',
    description: 'Gambian Dalasi',
    fractionDigits: 2,
    countryCode: 'GM',
  },
  {
    code: 'GNF',
    description: 'Guinean Franc',
    fractionDigits: 0,
    countryCode: 'GN',
  },
  {
    code: 'HTG',
    description: 'Haitian Gourde',
    fractionDigits: 2,
    countryCode: 'HT',
  },
  {
    code: 'IQD',
    description: 'Iraqi Dinar',
    fractionDigits: 2,
    countryCode: 'IQ',
  },
  {
    code: 'JOD',
    description: 'Jordanian Dinar',
    fractionDigits: 3,
    countryCode: 'JO',
  },
  {
    code: 'KES',
    description: 'Kenyan Shilling',
    fractionDigits: 2,
    countryCode: 'KE',
  },
  {
    code: 'KGS',
    description: 'Kyrgyzstani Som',
    fractionDigits: 2,
    countryCode: 'KG',
  },
  {
    code: 'KWD',
    description: 'Kuwaiti Dinar',
    fractionDigits: 3,
    countryCode: 'KW',
  },
  {
    code: 'LAK',
    description: 'Laos Kip',
    fractionDigits: 2,
    countryCode: 'LA',
  },
  {
    code: 'LBP',
    description: 'Lebanese Pound',
    fractionDigits: 2,
    countryCode: 'LB',
  },
  {
    code: 'LKR',
    description: 'Sri Lankan Rupee',
    fractionDigits: 2,
    countryCode: 'LK',
  },
  {
    code: 'LSL',
    description: 'Lesotho Loti',
    fractionDigits: 2,
    countryCode: 'LS',
  },
  {
    code: 'MDL',
    description: 'Moldovan Leu',
    fractionDigits: 2,
    countryCode: 'MD',
  },
  {
    code: 'MGA',
    description: 'Malagasy Ariary',
    fractionDigits: 0,
    countryCode: 'MG',
  },
  {
    code: 'MKD',
    description: 'Macedonian Denar',
    fractionDigits: 2,
    countryCode: 'MK',
  },
  {
    code: 'MMK',
    description: 'Myanmar Kyat',
    fractionDigits: 2,
    countryCode: 'MM',
  },
  {
    code: 'MOP',
    description: 'Macanese Pataca',
    fractionDigits: 2,
    countryCode: 'MO',
  },
  {
    code: 'MUR',
    description: 'Mauritian Rupee',
    fractionDigits: 2,
    countryCode: 'MU',
  },
  {
    code: 'MVR',
    description: 'Maldivian Rufiyaa',
    fractionDigits: 2,
    countryCode: 'MV',
  },
  {
    code: 'MWK',
    description: 'Malawian Kwacha',
    fractionDigits: 2,
    countryCode: 'MW',
  },
  {
    code: 'MZN',
    description: 'Mozambican Metical',
    fractionDigits: 2,
    countryCode: 'MZ',
  },
  {
    code: 'NAD',
    description: 'Namibian Dollar',
    fractionDigits: 2,
    countryCode: 'NA',
  },
  {
    code: 'NGN',
    description: 'Nigerian Naira',
    fractionDigits: 2,
    countryCode: 'NG',
  },
  {
    code: 'NIO',
    description: 'Nicaraguan Cordoba',
    fractionDigits: 2,
    countryCode: 'NI',
  },
  {
    code: 'NPR',
    description: 'Nepalese Rupee',
    fractionDigits: 2,
    countryCode: 'NP',
  },
  {
    code: 'OMR',
    description: 'Omani Rial',
    fractionDigits: 3,
    countryCode: 'OM',
  },
  {
    code: 'PAB',
    description: 'Panama Balboa',
    fractionDigits: 2,
    countryCode: 'PA',
  },
  {
    code: 'PEN',
    description: 'Peruvian Sol',
    fractionDigits: 2,
    countryCode: 'PE',
  },
  {
    code: 'PGK',
    description: 'Papua New Guinean Kina',
    fractionDigits: 2,
    countryCode: 'PG',
  },
  {
    code: 'PKR',
    description: 'Pakistani Rupee',
    fractionDigits: 2,
    countryCode: 'PK',
  },
  {
    code: 'PYG',
    description: 'Paraguayan Guarani',
    fractionDigits: 0,
    countryCode: 'PY',
  },
  {
    code: 'RSD',
    description: 'Serbian Dinar',
    fractionDigits: 2,
    countryCode: 'RS',
  },
  {
    code: 'RWF',
    description: 'Rwandan Franc',
    fractionDigits: 0,
    countryCode: 'RW',
  },
  {
    code: 'SBD',
    description: 'Solomon Islands Dollar',
    fractionDigits: 2,
    countryCode: 'SB',
  },
  {
    code: 'SCR',
    description: 'Seychelles Rupee',
    fractionDigits: 2,
    countryCode: 'SC',
  },
  {
    code: 'SRD',
    description: 'Surinamese Dollar',
    fractionDigits: 2,
    countryCode: 'SR',
  },
  {
    code: 'TMT',
    description: 'Turkmenistani New Manat',
    fractionDigits: 2,
    countryCode: 'TM',
  },
  {
    code: 'TND',
    description: 'Tunisian Dinar',
    fractionDigits: 3,
    countryCode: 'TN',
  },
  {
    code: 'TOP',
    description: "Tongan Pa'anga",
    fractionDigits: 2,
    countryCode: 'TO',
  },
  {
    code: 'TTD',
    description: 'Trinidadian Dollar',
    fractionDigits: 2,
    countryCode: 'TT',
  },
  {
    code: 'TWD',
    description: 'Taiwanese New Dollar',
    fractionDigits: 2,
    countryCode: 'TW',
  },
  {
    code: 'TZS',
    description: 'Tanzanian Shilling',
    fractionDigits: 2,
    countryCode: 'TZ',
  },
  {
    code: 'UAH',
    description: 'Ukrainian Hryvnia',
    fractionDigits: 2,
    countryCode: 'UA',
  },
  {
    code: 'UGX',
    description: 'Ugandan Shilling',
    fractionDigits: 2,
    countryCode: 'UG',
  },
  {
    code: 'UYU',
    description: 'Uruguayan Peso',
    fractionDigits: 2,
    countryCode: 'UY',
  },
  {
    code: 'VND',
    description: 'Vietnamese Dong',
    fractionDigits: 0,
    countryCode: 'VN',
  },
  {
    code: 'XAF',
    description: 'Central African Franc',
    fractionDigits: 0,
    countryCode: 'CM',
  },
  {
    code: 'XOF',
    description: 'West African Franc',
    fractionDigits: 2,
    countryCode: 'SN',
  },
  {
    code: 'XPF',
    description: 'Central Pacific Franc',
    fractionDigits: 0,
    countryCode: 'PF',
  },
  {
    code: 'ZMW',
    description: 'Zambian Kwacha',
    fractionDigits: 2,
    countryCode: 'ZM',
  },
]
