export enum DateFormat {
  ApiRequest = 'yyyy-MM-dd',
  InputMask = 'dd/MM/yyyy',
  DayMonthYear = 'dd/MM/yyyy',
  MonthDayYear = 'MM/dd/yyyy',
  CardExpireDate = 'MM/yyyy',
  CardExpireDateShort = 'MM/yy',
  CardOrderCreatedDate = 'p, ccc, d MMMM',
  EstimatedCardDeliveryTime = 'ccc, do LLL',
  PortfolioTransactionDatetime = 'd MMM, p',
  PortfolioTransactionDateWithYear = 'd MMM, yyy',
  TransactionsFilterOptionWithMonthAndYear = 'MMMM yyyy',
  TransactionsFilterOptionWithYear = 'yyyy',
  TransactionsFilterOptionWithMonth = 'LLLL',
  TransactionsFilterOptionDay = 'd',
  TransactionsGroupDateWithYear = 'iii, d MMMM yyyy',
  TransactionsGroupDate = 'iii, d MMMM',
  TransactionsBankTransferProgressDateShortAndTime = 'MMM d HH:mm',
  TransactionsBankTransferProgressDateShort = 'MMM d',
  TransactionsBankTransferProgressDateLong = 'MMM d yyyy',
  TransactionsBankTransferProgressTime = 'HH:mm',
  LocalTime = 'HH:mm:ss',
  VaultDeadline = 'd MMMM y',
  VaultPaymentDate = 'MMM d, yyyy',
}
