import { Language } from "../constants"

const TRANSLATIONS: Record<string, { [L in Language]?: string }> = {
  " results": { ja: "件", ko: "결과" },
  ".": { ja: "。" },
  '<p><a href="/account">View your profile</a> or</p>': {
    ja: '<p><a href="/account">プロフィールを見る</a>か</p>',
  },
  "<p>A DeFi powered game: Get spaceships, explore the galaxy, and earn tokens!</p>":
    {
      ja: "<p>DeFiを搭載したゲーム。宇宙船を手に入れて、銀河を探索し、トークンを稼ごう!</p>",
    },
  "<p>Adopt an Axie today!</p>": {
    ja: "<p>今すぐAxieを飼おう！</p>",
    ko: "<p>오늘, Axie를 입양하세요!</p>",
  },
  "<p>Art Blocks are unique works generated by on-chain algorithms. Collect art from top generative artists!</p>":
    {
      ja: "<p>アートブロックは、オンチェーンアルゴリズムによって生成されたユニークな作品です。トップジェネレーティブアーティストからアートを集めよう</p>",
    },
  "<p>Asteroids full of tokens await</p>": {
    ja: "<p>トークンがいっぱいの小惑星が待っている</p>",
  },
  "<p>Atari NFT Fashion Line</p>": { ja: "<p>アタリNFTファッションライン</p>" },
  "<p>Axies are fierce fantasy pets that love to battle.\r\nBuild unstoppable teams and conquer your enemies!</p>":
    {
      ja: "<p>Axieはバトルが大好きな激しいファンタジーペットです。\r\n止められないチームを作り、敵を征服しよう！</p>",
      ko: "<p>Axie는 전투를 사랑하는 환상 속의 무서운 펫입니다.\r\n멈추지 않는 팀을 만들어 적을 점령하세요!</p>",
    },
  "<p>Become a JOY Collector</p>": {
    ja: "<p>JOYコレクターになろう</p>",
    ko: "<p>JOY 콜렉터가 되어보세요</p>",
  },
  "<p>Beeple portraits by The Most Famous Artist</p>": {
    ja: "<p>The Most Famous Artistによるビープルの肖像画</p>",
  },
  "<p>Blockchain technology changes the way we make, trade, and enjoy art. With provenance recorded and stored on a distributed ledger, market power is shifting back to the creators.</p>":
    {
      ja: "<p>ブロックチェーン技術は、私たちがアートを作り、取引し、楽しむ方法を変えます。実績が記録され、分散型台帳に保存されることで、市場の力はクリエイターに戻りつつあります。</p>",
      ko: "<p>블록체인 기술은 우리가 예술을 창작하고, 거래하고, 향유하는 방식을 변화시킵니다. 작품의 소장 이력이 분산 원장에 기록·저장됨에 따라 시장 지배력은 다시 창작자에게 돌아가고 있습니다.</p>",
    },
  "<p>Collect 1-1 JOYs created by the artist John Orion Young.</p>": {
    ja: "<p>アーティストのジョン・オリオン・ヤングが制作した1-1のJOYを集めよう。</p>",
    ko: "<p>존 오리온 영이 만든 1-1 JOY를 모아보세요</p>",
  },
  '<p>Every week, developers, creators, artists, and influencers are launching brand new collections on OpenSea. If you’d like to create your own collection, visit the <a href="/collections">collection manager page</a>.</p>':
    {
      ja: '<p>毎週、開発者、クリエイター、アーティスト、インフルエンサーがOpenSea上で新しいコレクションを発表しています。独自のコレクションを作成したい場合は、<a href="/collections">コレクションマネージャーのページ</a>にアクセスしてください。</p>',
      ko: '<p>개발자, 제작자, 아티스트 및 인플루언서가 OpenSea에서 매주 새로운 컬렉션을 출시합니다. 나만의 컬렉션을 만들고 싶다면 <a href="/collections">컬렉션 관리자 페이지를</a> 방문하세요.</p>',
    },
  "<p>Generative abstract by pxlq. Rendered in 4K.</p>": {
    ja: "<p>pxlqによる生成抽象。4Kでレンダリング。</p>",
    ko: "<p>pxlq에 의한 생성 요약. 4K로 렌더링되었습니다.</p>",
  },
  "<p>Google: &#x27;The Most Famous Artist&#x27;</p>": {
    ja: "<p>グーグル：「最も有名なアーティスト</p>",
  },
  "<p>Grab a Neon Pizza Box and receive exclusive NFT armor, physical Neon District branded clothing, cyberpunk accessories, and a boost in NEON rewards.</p>":
    {
      ja: "<p>ネオンピザボックスを手に入れて、限定のNFTアーマー、物理的なネオン地区ブランドの服、サイバーパンクアクセサリー、そしてNEON報酬のブーストを手に入れよう。</p>",
      ko: "<p>Neon Pizza Box를 들고 독점 NFT 갑옷, 실제 Neon District 브랜드 의류, 사이버 펑크 액세서리 및 NEON 보상 부스트를 받으세요.</p>",
    },
  "<p>Join the Neon Pizza Party</p>": {
    ja: "<p>ネオンピザパーティーに参加</p>",
    ko: "<p>네온 피자 파티에 참여하세요</p>",
  },
  "<p>More than just collectibles, these Atari NFT&#x27;s will be usable in-game &amp; in the real world. Dress your in-game avatar or add to your latest selfie!</p>":
    {
      ja: "<p>単なるコレクターズアイテムではなく、これらのアタリNFTはゲーム内でも現実世界でも使えるようになります。ゲーム内のアバターに着せ替えたり、最新のセルフィーに加えたりしよう！</p>",
    },
  "<p>Now is your chance to collect one of a kind NFTs from The Most Famous Artist.</p>":
    {
      ja: "<p>The Most Famous Artistから一点もののNFTを集めるチャンスです。</p>",
    },
  "<p>Own a 1 of 1 of X</p>": { ja: "<p>Xの1/1を所有する</p>" },
  "<p>PXLQ // 4K</p>": { ja: "<p>PXLQ // 4K</p>", ko: "<p>PXLQ // 4K</p>" },
  "<p>Pioneers of NFT Farming, $MEME invites you to join the community innovating in DeFi and NFT art.</p>":
    {
      ja: "<p>NFT農業のパイオニア、$MEMEはあなたがDeFiとNFTアートで革新的なコミュニティに参加するために招待します。</p>",
    },
  "<p>The blockchain plays host to a range of collectibles from some of the biggest sporting brands in the world. From soccer to golf, digital assets are changing the way fans interact with their favorites.</p>":
    {
      ja: "<p>ブロックチェーンは、世界最大のスポーツブランドの様々なグッズをホストしています。サッカーからゴルフまで、デジタル資産はファンのお気に入りとの関わり方を変えつつあります。</p>",
      ko: "<p>블록체인은 세계 최대 스포츠 브랜드의 다양한 수집품을 호스팅합니다. 축구에서 골프에 이르기까지 디지털 자산은 팬들이 자신의 ‘최애’와 상호작용하는 방식을 바꾸고 있습니다.</p>",
    },
  "<p>The way we understand value is changing before our eyes. From breedable kittens to cryptographic stamps, our innate desire to collect is going digital.</p>":
    {
      ja: "<p>私たちが価値を理解する方法は、目の前で変化しています。繁殖可能な子猫から暗号切手まで、私たちの生来の収集欲求はデジタル化しています。</p>",
      ko: "<p>우리가 알고 있던 가치의 개념이 눈 앞에서 변하고 있습니다. 아기 고양이에서 크립토 우표에 이르기까지 우리의 본능적인 수집 욕구가 디지털화되고 있습니다.</p>",
    },
  "<p>The world&#x27;s largest collection of Beeple portraits exclusively available on Opensea.</p>":
    {
      ja: "<p>世界最大級のビープルの肖像画コレクションはオープンシーでしか手に入らない。</p>",
    },
  "<p>Trading cards have been dragged into the 21st century. With unique assets traded and stored on the blockchain, classic games are taking on a new life.</p>":
    {
      ja: "<p>トレーディングカードは21世紀に引きずり込まれました。ブロックチェーン上で取引され、保存されるユニークな資産により、古典的なゲームは新たな人生を歩もうとしています。</p>",
      ko: "<p>트레이딩 카드가 21세기로 넘어 왔습니다. 고유한 자산이 거래되고 블록체인에 저장되면서 클래식 게임의 활기가 되살아났습니다.</p>",
    },
  "<p>Turning hexadecimal wallet addresses into human-readable names is big business in crypto. Browse thousands of censorship-resistant domain names right here on OpenSea.</p>":
    {
      ja: "<p>16進数のウォレットアドレスを人間が読める名前に変換することは、暗号の世界では大きなビジネスとなっています。OpenSeaで何千もの検閲に強いドメイン名を閲覧できます。</p>",
      ko: "<p>16진수 지갑 주소를 사람이 읽을 수 있는 이름으로 바꾸는 것은 크립토 산업의 핵심 중 하나입니다. OpenSea에서 수천 개의 검열 방지 도메인 이름을 찾아보세요.</p>",
    },
  "<p>Uh, what&#x27;s with the pineapple?</p>": {
    ja: "<p>えーと、このパイナップルは？</p>",
  },
  "<p>Virtual worlds allow users to create and trade valuable blockchain-backed NFTs in ever-evolving digital realities. These online public spaces are built and maintained by the crypto community.</p>":
    {
      ja: "<p>バーチャルワールドでは、ユーザーは進化し続けるデジタルリアリティの中で、価値あるブロックチェーンでバックアップされたNFTを作成し、取引することができます。これらのオンラインのパブリックスペースは、暗号コミュニティによって構築され、維持されています。</p>",
      ko: "<p>사용자는 가상 세계를 통해 끊임없이 진화하는 디지털 현실에서 가치있는 블록체인 기반 NFT를 만들고 거래 할 수 있습니다. 이 온라인 공간은 크립토 커뮤니티에서 구축하고 관리합니다.</p>",
    },
  '<p>We&#x27;ll send you an e-mail when it goes through. In the meantime, <a href="/assets/">check out other items on OpenSea</a>.</p>':
    {
      ja: '<p>それが通過したらメールでお知らせします。それまでの間、<a href="/assets/">OpenSeaの他のアイテムをチェックして</a>みてください。</p>',
    },
  "<p>Whether it&#x27;s redeemable rewards or membership NFTs, a rising number of creators and developers are leveraging blockchain-backed tokens to build and support their communities.</p>":
    {
      ja: "<p>換金可能なリワードであれ、メンバーシップNFTであれ、ブロックチェーンを利用したトークンを活用してコミュニティを構築し、サポートするクリエイターや開発者が増えています。</p>",
      ko: "<p>점점 더 많은 창작자와 개발자들이 포인트나 멤버십 NFT 등 블록체인 기반 토큰을 활용하여 커뮤니티를 구축하고 지원하고 있습니다.</p>",
    },
  "<x0>42</x0> owned by <x4>Alice</x4>": {
    ja: "<x4>アリス</x4>が<x0>42</x0>個を所有している",
  },
  "About <x2>OpenSea Creatures</x2>": {
    ja: "<x2>オープンシーの生き物</x2>について",
  },
  "Account Settings": { ja: "アカウント設定", ko: "계정 설정" },
  Activity: { ja: "活動", ko: "활동" },
  "All Items": { ja: "すべて", ko: "모든 아이템" },
  Amount: { ja: "金額" },
  "Amount of ETH in sales": { ja: "ETHの売買高" },
  Art: { ja: "アート", ko: "아트" },
  "Authorizing your account for this order...": {
    ja: "この注文のためにあなたのアカウントを承認する...",
  },
  "Average Price": { ja: "平均価格" },
  "Average price of items in this collection": {
    ja: "このコレクションのアイテムの平均価格",
  },
  "BUY NOW": { ja: "今すぐ購入", ko: "지금 구입" },
  "Back to all items": { ja: "すべてのアイテムに戻る" },
  Blog: { ja: "ブログ", ko: "블로그" },
  Boosts: { ja: "ブースト" },
  Browse: { ja: "閲覧", ko: "검색" },
  Bundles: { ja: "バンドル", ko: "묶음" },
  "Buy Now": { ja: "今すぐ購入", ko: "지금 구매하기" },
  "Buy, sell, and discover rare digital items": {
    ja: "レアなデジタルアイテムの売買・発見",
    ko: "희귀한 디지털 아이템을 구매, 판매 또는 탐색해보세요",
  },
  "Buy, sell, discover, and trade limited-edition goods": {
    ja: "限定商品の購入・販売・発見・取引",
    ko: "한정판을 사고, 팔고, 찾고, 교환하세요",
  },
  Careers: { ja: "採用情報", ko: "채용" },
  Categories: { ja: "カテゴリー" },
  "Chain Info": { ja: "チェーン情報" },
  Chains: { ja: "ブロックチェーン" },
  "Chat with us": { ja: "チャット", ko: "채팅하기" },
  Cheapest: { ja: "最も安い", ko: "가장 저렴" },
  Checkout: { ja: "チェックアウト" },
  Collectibles: { ja: "グッズ", ko: "수집 아이템" },
  Collections: { ja: "コレクション", ko: "컬렉션" },
  Community: { ja: "コミュニティ", ko: "커뮤니티" },
  "Completing the trade...": { ja: "取引を実行する..." },
  Create: { ja: "作成", ko: "만들기" },
  "Created by <x1>Alice</x1>": { ja: "作成者：<x1>アリス</x1>" },
  "Current price": { ja: "現在の価格" },
  Details: { ja: "詳細" },
  "Develop with us": { ja: "開発", ko: "함께 개발하기" },
  Developers: { ja: "開発者", ko: "개발자 메뉴" },
  "Digital Art": { ja: "デジタルアート", ko: "디지털 아트" },
  Docs: { ja: "ドキュメント", ko: "개발 문서" },
  "Domain Names": { ja: "ドメイン名", ko: "도메인 이름" },
  "Ending Soon": { ja: "間もなく終了", ko: "곧 종료" },
  "Enter an email and username, so we can let you know when it gets included in the blockchain:":
    {
      ja: "電子メールとユーザー名を入力してください。",
    },
  "Enter your bid to become the highest bidder for this auction. Note that OpenSea will only auto-fulfill bids above 1 ETH in value when gas prices are moderate or low - otherwise, the seller must accept your bid.":
    {
      ja: "入札すると、このオークションの最高入札者になります。OpenSeaは、ガス価格が中程度または低価格の場合にのみ、1ETH以上の入札を自動的に行うことに注意してください。そうではない場合、販売者が入札を受け入れる必要があります。",
    },
  Explore: { ja: "探索", ko: "탐색하기" },
  FAQ: { ja: "よくあるご質問", ko: "자주 묻는 질문과 답변" },
  Filter: { ja: "フィルター", ko: "필터" },
  "For Sale": { ja: "販売", ko: "판매" },
  "Has Offers": { ja: "オファーあり", ko: "오퍼 있음" },
  Help: { ja: "ヘルプ", ko: "도움말" },
  "Help Center": { ja: "ヘルプセンター", ko: "고객 센터" },
  "Here's a summary of your purchase:": { ja: "購入のまとめです。" },
  "Highest Last Sale": { ja: "最高最終販売", ko: "가장 높은 마지막 판매" },
  'If a signature request pops up, just click "Sign" to verify that you own your wallet.':
    {
      ja: "サインのリクエストがポップアップしたら、「サイン」をクリックするだけで、自分の財布を所有していることを確認することができます。",
    },
  "In Wallet": { ja: "財布の中" },
  Item: { ja: "項目" },
  Items: { ja: "アイテム数" },
  Last: { ja: "前価格", ko: "마지막" },
  "Learn more about offers": { ja: "オファーの詳細はこちら" },
  Levels: { ja: "レベル" },
  Listings: { ja: "リスティング" },
  "Log out": { ja: "ログアウト", ko: "로그 아웃" },
  "Make Offer": { ja: "申し出をする" },
  "Make an offer": { ja: "申し出をする" },
  "Min Bid": { ja: "最小入札額", ko: "최소 입찰가" },
  "Most Viewed": { ja: "最も閲覧された", ko: "가장 많이 본" },
  "My Collections": { ja: "マイコレクション ", ko: "나의 컬렉션" },
  "My Profile": { ja: "プロフィール", ko: "나의 프로필" },
  New: { ja: "新着", ko: "신작" },
  "New Collections": { ja: "新着コレクション", ko: "새 컬렉션" },
  "Number of accounts who own items in this collection": {
    ja: "このコレクションのアイテムを所有しているアカウント数",
  },
  "Number of items in this collection": { ja: "このコレクションのアイテム数" },
  "Offer Expiration": { ja: "オファー期限" },
  "Offer for": { ja: "現在オファー", ko: "제안" },
  Offers: { ja: "オファー" },
  Oldest: { ja: "最古", ko: "가장 오래된" },
  "On Auction": { ja: "オークション", ko: "경매 중" },
  "On Sale In": { ja: "通貨", ko: "판매 중" },
  "Owned by <x1>Alice</x1>": { ja: "所有者：<x1>アリス</x1>" },
  Owners: { ja: "所有者" },
  "Place Bid": { ja: "入札する" },
  "Place a bid": { ja: "入札する" },
  Price: { ja: "価格", ko: "가격" },
  "Price History": { ja: "価格履歴" },
  Properties: { ja: "所有特性" },
  Quantity: { ja: "数量" },
  Rankings: { ja: "ランキング", ko: "랭킹" },
  "Recently Created": { ja: "最近作成された", ko: "최근 생성" },
  "Recently Listed": { ja: "最近上場した", ko: "최근 상장" },
  "Recently Received": { ja: "最近受信したもの" },
  "Recently Sold": { ja: "最近販売された", ko: "최근 판매" },
  Referrals: { ja: "照会" },
  "Search OpenSea": { ja: "OpenSeaを検索" },
  "Search items, collections, and accounts": {
    ja: "アイテム、コレクション、アカウントの検索",
    ko: "아이템, 컬렉션, 계정 검색하기",
  },
  Sell: { ja: "売る", ko: "판매하기" },
  "Single Items": { ja: "単品", ko: "단일 품목" },
  "Sort by": { ja: "並び替え", ko: "정렬 기준" },
  Sports: { ja: "スポーツ", ko: "스포츠" },
  Stats: { ja: "統計" },
  Status: { ja: "ステータス", ko: "상태" },
  "Submit NFTs": { ja: "NFTの提出", ko: "NFT 등록하기" },
  Suggestions: { ja: "提案", ko: "제안" },
  "The Ethereum network is processing your transaction, which can take a little while.":
    {
      ja: "Ethereumネットワークがあなたの取引を処理しているので、少し時間がかかることがあります。",
    },
  "The largest NFT marketplace": {
    ja: "最大のNFTマーケットプレイス",
    ko: "가장 큰 NFT 마켓 플레이스",
  },
  "The largest marketplace for <strong>rare items</strong>": {
    ja: "<strong>レアアイテムの</strong>最大のマーケットプレイス",
    ko: "<strong>레어 아이템을 사고파는</strong>가장 큰 마켓",
  },
  "This collection has no description yet. Contact the owner of this collection about setting it up on OpenSea!":
    {
      ja: "このコレクションにはまだ説明がありません。OpenSeaでの設定については、このコレクションの所有者に連絡してください!",
    },
  "Top Bid": { ja: "現在入札額", ko: "최고 입찰가" },
  "Top Collections": { ja: "トップコレクション", ko: "상위 컬렉션" },
  Total: { ja: "合計" },
  Traded: { ja: "売買高" },
  "Trading Cards": { ja: "トレーディングカード", ko: "트레이딩 카드" },
  "Trading History": { ja: "取引履歴" },
  Transfer: { ja: "転送", ko: "양도하기" },
  Utility: { ja: "ユーティリティ", ko: "유틸리티" },
  "View all": { ja: "すべてを見る", ko: "모두 보기" },
  "View on Etherscan": { ja: "イースキャンで見る" },
  "Virtual Worlds": { ja: "バーチャルワールド", ko: "가상 세계" },
  "W-ETH Station": { ja: "W-ETH両替", ko: "W-ETH 스테이션" },
  "Waiting for blockchain confirmation...": {
    ja: "ブロックチェーンの確認を待っている...。",
  },
  "Welcome to the home of <x2>Colorglyphs</x2> on OpenSea. Discover the best items in this collection.":
    {
      ja: "OpenSeaの<x2>カラーグリフ</x2>のページへようこそ。このコレクションの最高のアイテムを探しましょう。",
    },
  "Your transaction has started": { ja: "あなたの取引が開始されました" },
  "Your transaction succeeded!": { ja: "あなたの取引は成功しました" },
  "buy now": { ja: "今買う", ko: "지금 구매" },
  "collection manager page": { ja: "コレクションマネージャページ" },
  new: { ja: "new", ko: "new" },
  you: { ja: "あなた" },
}
export default TRANSLATIONS
