export enum ProductTourSteps {
    ACCOUNT_SUMMARY = 'ACCOUNT_SUMMARY',
    ACTIVITY = 'ACTIVITY',
    CASH_ORDER = 'CASH_ORDER',
    PRODUCTS_SEARCH = 'QUICK_SEARCH',
    QUICK_ORDER = 'QUICK_ORDER'
}
