export const AnalyticsEvent = {
  ACCESS_RECOVERY_STEP: 'AccessRecoveryStep',
  ACCESS_RECOVERY_SUBMIT: 'AccessRecoverySubmit',
  SMART_FAQ_LINK_CLICKED: 'Smart faq link clicked',
  SURVEY_RATE: 'survey rate',
  SURVEY_SUCCESS_SCREEN: 'survey success screen',
  REOPEN: 're-open',
  START_NEW_CHAT: 'Start new chat',
  HIDE_ALL_CHATS: 'hide all chats',
  VIEW_ALL_CHATS: 'view all chats',
  OPEN_MESSAGE_PREVIEW: 'open message preview',
  CLOSE_MESSAGE_PREVIEW: 'close message preview',
  LANG_AVAILABILITY_BANNER_CLOSED: 'LangAvailBnr Close',
  LANG_AVAILABILITY_BANNER_OPENED: 'LangAvailBnr Open',
  LANG_AVAILABILITY_BANNER_TO_ENG: 'LangAvailBnr To Eng',
  LANG_AVAILABILITY_BANNER_TO_HELP_CENTRE: 'LangAvailBnr To HC',
  BACK_BUTTON: 'back button',
  HELP_CENTRE: 'Help centre',
  CHAT_LIST: 'Chat list',
  PRE_CHAT_BANNER_REQUESTS_PENDING_OPENED: 'PreChatBanner - Req pending',
  PRE_CHAT_BANNER_REQUESTS_SUBMITTED_OPENED: 'PreChatBanner - Req submitted',
  PRE_CHAT_BANNER: 'PreChatBanner',
  PRE_CHAT_BANNER_PRIMARY_CTA_CLICKED: 'PreChatBanner - PrimaryCta',
  PRE_CHAT_BANNER_SECONDARY_CTA_CLICKED: 'PreChatBanner - SecondaryCta',
  ACCESS_RECOVERY_SMS: 'Access Recovery SMS',
  ACCESS_RECOVERY_EMAIL: 'Access Recovery EMAIL',
  ACCESS_RECOVERY_PASSWORD: 'Access Recovery PASSWORD',
  FILE_DOWNLOAD: 'File download',
}
