export const exampleFaqRanks = {
  'question.activating-my-card': 0,
  'question.additional-information-needed-for-onboarding': -5,
  'question.can-i-transfer-money-from-my-paypal-account-to-my-revolut-for-business-card': -2,
  'question.creating-a-business-account': -5,
  'question.how-quick-is-my-transfer': -1,
  'question.making-a-bank-transfer': 4,
  'question.my-physical-card-is-not-working': -1,
  'question.ordering-a-new-physical-card': 11,
  'question.transferring-money-into-my-account': 4,
  'question.unsupported-inbound-transfers': -4,
  'question.what-are-the-transfer-limits': -2,
  'question.what-if-i-have-negative-account-balances': 0,
  'question.what-if-my-account-is-blocked': -13,
  'question.what-industries-are-not-supported': -5,
  'question.what-is-the-withdrawal-limit': 0,
  'question.what-is-the-withdrawing-limit': 0,
  'question.what-s-the-billing-address-of-my-physical-card': -2,
  'question.what-type-of-loans-does-revolut-offer': 1,
  'question.what-types-of-business-entities-are-supported': -5,
  'question.where-can-i-transfer-money': -1,
  'question.why-has-my-card-payment-been-declined': 0,
  'question.why-is-my-card-payment-still-pending': -4,
  'question.will-i-be-charged-for-transferring-money': -1,
}
